# Generated by Django 3.1 on 2020-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collab_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=75)),
                ('p_desc', models.CharField(max_length=200)),
                ('p_prerequisite', models.CharField(default='No prerequisite required', max_length=200)),
                ('p_level', models.CharField(default='Beginner', max_length=20)),
                ('p_category', models.CharField(default='Beginner', max_length=30)),
                ('p_part', models.IntegerField()),
                ('p_image', models.ImageField(default='', upload_to='project/media')),
            ],
        ),
    ]
